version: '3.4'

x-common: &common
  stdin_open: true
  tty: true
  restart: unless-stopped
  networks:
    - project

x-django-build: &django-build
  build:
    context: .
    dockerfile: ./Dockerfile.stage

services:

  celery:
    <<: *django-build
    container_name: project-cc01
    restart: unless-stopped
    command: bash -c "celery -A project worker -l info"
    depends_on:
      - django
      - redis
    env_file:
      - ./config/env/stage/.django
    volumes:
      - .:/code/
    <<: *common

  celery_beat:
    <<: *django-build
    container_name: project-cb01
    restart: unless-stopped
    command: bash -c "celery -A project beat -l info"
    depends_on:
      - django
      - redis
    env_file:
      - ./config/env/stage/.django
    volumes:
      - .:/code/
    <<: *common

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  django:
    <<: *django-build
    container_name: project-dc01
    restart: unless-stopped
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./config/env/stage/.django
    volumes:
      - ./:/code
      - project_static_volume:/code/static
      - project_media_volume:/code/media
    depends_on:
      - postgres
    <<: *common

  flower:
    image: mher/flower:0.9.7
    container_name: project-fc01
    restart: unless-stopped
    command: ["flower", "--broker=redis://redis:6379/0", "--broker_api=redis://redis:6379/0", "--port=5555"]
    ports:
      - 5555:5555
    <<: *common

  nginx:
    image: nginx:1.20.1
    container_name: project-nc01
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./config/nginx/stage/conf.d:/etc/nginx/conf.d/default.conf
      - project_static_volume:/code/static
      - project_media_volume:/code/media
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - django
#    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    <<: *common

  postgres:
    image: postgres:13.3-buster
    container_name: project-pc01
    restart: unless-stopped
    env_file:
      - ./config/env/stage/.postgres
    ports:
      - 5432:5432
    volumes:
      - project_postgres_data:/var/lib/postgresql/data/
    <<: *common

  redis:
    image: redis:6.2-buster
    container_name: project-rc01
    restart: unless-stopped
    volumes:
      - project_redis_data:/data
    <<: *common

networks:
  project:
    driver: bridge

volumes:
  project_postgres_data:
  project_redis_data:
  project_static_volume:
  project_media_volume: