version: "3.4"

x-common: &common
  stdin_open: true
  tty: true
  restart: unless-stopped

x-django-build: &django-build
  build:
    context: .
    args:
      REQUIREMENT_FILE: $REQUIREMENT_FILE

services:
  django:
    <<: *django-build
    env_file:
      - ./config/env/.test
    volumes:
      - ./:/code
      - project_static_volume:/code/static
      - project_media_volume:/code/media
    depends_on:
      - postgres
      - redis
    <<: *common

  postgres:
    image: postgres:13.3-buster
    env_file:
      - ./config/env/.test
    ports:
      - "5432"
    volumes:
      - project_postgres_data:/var/lib/postgresql/data/
    <<: *common

  redis:
    image: redis:6.2-buster
    ports:
      - "6379"
    volumes:
      - project_redis_data:/data
    <<: *common

volumes:
  project_postgres_data:
  project_redis_data:
  project_static_volume:
  project_media_volume:
