version: "3.4"

x-common: &common
  stdin_open: true
  tty: true
  restart: unless-stopped

x-django-build: &django-build
  build:
    context: .
    args:
      REQUIREMENT_FILE: $REQUIREMENT_FILE

services:
  celery:
    <<: [*django-build, *common]
    command: bash -c "celery -A $PROJECT worker -l info"
    depends_on:
      - django
      - redis
    env_file:
      - .env
    volumes:
      - ./:/code

  celery_beat:
    <<: [*django-build, *common]
    command: bash -c "celery -A $PROJECT beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - django
      - redis
    env_file:
      - .env
    volumes:
      - ./:/code

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    <<: *common

  django:
    <<: [*django-build, *common]
    command: bash -c "gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers $GUNICORN_WORKERS --worker-class gthread --threads $GUNICORN_THREADS"
    ports:
      - "8000"
    env_file:
      - .env
    volumes:
      - ./:/code
    depends_on:
      - postgres
      - redis

  flower:
    <<: [*django-build, *common]
    command: bash -c "celery -A $PROJECT flower --conf=/code/config/settings/flowerconfig.py"
    ports:
      - "5555"
    depends_on:
      - celery
      - redis
    env_file:
      - .env
    volumes:
      - .:/code/

  nginx:
    image: nginx:1.20.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - django
      - flower
    env_file:
      - .env
    #    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    <<: *common

  redis:
    image: redis:7.2-bookworm
    ports:
      - "6379"
    volumes:
      - ${PROJECT}_redis_data:/data
    <<: *common

volumes:
  project_redis_data:
  project_static_volume:
  project_media_volume:
