version: "3.4"

x-common: &common
  stdin_open: true
  tty: true
  restart: unless-stopped

x-django-build: &django-build
  build:
    context: .
    args:
      REQUIREMENT_FILE: $REQUIREMENT_FILE
      USER: $USER

services:
  celery:
    <<: *django-build
    command: bash -c "python3 -m celery -A $PROJECT worker -l info"
    depends_on:
      - django
      - redis
    env_file:
      - $ENV_FILE
    volumes:
      - ./:/home/${USER}/code
      - ./data/django-media:/code/media
    <<: *common

  celery_beat:
    <<: *django-build
    command: bash -c "python3 -m celery -A $PROJECT beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - django
      - redis
    env_file:
      - $ENV_FILE
    volumes:
      - ./:/home/${USER}/code
      - ./data/django-media:/code/media
    <<: *common

  django:
    <<: *django-build
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - $ENV_FILE
    volumes:
      - ./:/home/${USER}/code
      - ./data/django-static:/code/static
      - ./data/django-media:/code/media
      - ~/.gitconfig:/etc/gitconfig
      - ~/.ssh:/home/${USER}/.ssh:ro
    depends_on:
      - postgres
      - redis
    <<: *common

  flower:
    image: mher/flower:0.9.7
    command: bash -c "python3 -m celery -A $PROJECT --broker=$REDIS_URL/0 flower --url_prefix=flower --basic_auth=$FLOWER_USERNAME:$FLOWER_PASSWORD"
    ports:
      - "5555:5555"
    depends_on:
      - redis
    <<: *common

  postgres:
    image: postgres:13.3-buster
    env_file:
      - $ENV_FILE
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    <<: *common

  redis:
    image: redis:6.2-buster
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    <<: *common
