version: "3.4"

x-common: &common
  stdin_open: true
  tty: true
  restart: unless-stopped

x-django-build: &django-build
  build:
    context: .
    args:
      REQUIREMENT_FILE: $REQUIREMENT_FILE

services:
  celery:
    <<: [*django-build, *common]
    command: bash -c "celery -A $PROJECT worker -l info"
    depends_on:
      - django
      - redis
    env_file:
      - .env
    volumes:
      - ./:/code
      - project_media_volume:/code/media

  celery_beat:
    <<: [*django-build, *common]
    command: bash -c "celery -A $PROJECT beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - django
      - redis
    env_file:
      - .env
    volumes:
      - ./:/code
      - project_media_volume:/code/media

  certbot:
    image: certbot/certbot
    #    volumes:
    #      - ./data/certbot/conf:/etc/letsencrypt
    #      - ./data/certbot/www:/var/www/certbot
    ##    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    <<: *common

  django:
    <<: [*django-build, *common]
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000"
    env_file:
      - .env
    volumes:
      - ./:/code
      - project_static_volume:/code/static
      - project_media_volume:/code/media
    depends_on:
      - postgres
      - redis

  flower:
    <<: [*django-build, *common]
    command: bash -c "celery -A $PROJECT flower --conf=/code/config/settings/flowerconfig.py"
    ports:
      - "5555"
    depends_on:
      - celery
      - redis
    env_file:
      - .env
    volumes:
      - .:/code/

  nginx:
    image: nginx:1.20.1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/stage.conf:/etc/nginx/conf.d/default.conf
      - project_static_volume:/code/static
      - project_media_volume:/code/media
    #      - ./data/certbot/conf:/etc/letsencrypt
    #      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - django
      - flower
    #    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    <<: *common

  postgres:
    image: postgres:15.4-bookworm
    env_file:
      - .env
    ports:
      - "5432"
    volumes:
      - project_postgres_data:/var/lib/postgresql/data/
    <<: *common

  redis:
    image: redis:6.2-buster
    ports:
      - "6379"
    volumes:
      - project_redis_data:/data
    <<: *common

volumes:
  project_postgres_data:
  project_redis_data:
  project_static_volume:
  project_media_volume:
