version: "3.4"

x-common: &common
  stdin_open: true
  tty: true
  restart: unless-stopped

x-django-build: &django-build
  build:
    context: .
    args:
      REQUIREMENT_FILE: $REQUIREMENT_FILE

services:
  celery:
    <<: *django-build
    command: bash -c "celery -A $PROJECT worker -l info"
    depends_on:
      - django
      - redis
    env_file:
      - .env
    volumes:
      - ./:/code
      - project_media_volume:/code/media
    <<: *common

  celery_beat:
    <<: *django-build
    command: bash -c "celery -A $PROJECT beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - django
      - redis
    env_file:
      - .env
    volumes:
      - ./:/code
      - project_media_volume:/code/media
    <<: *common

  django:
    <<: *django-build
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/code
      - project_static_volume:/code/static
      - project_media_volume:/code/media
    depends_on:
      - postgres
      - redis
    <<: *common

  flower:
    <<: *django-build
    command: bash -c "celery -A $PROJECT --broker=${REDIS_URL}/0 flower --url_prefix=flower --basic_auth=${FLOWER_USERNAME}:${FLOWER_PASSWORD}"
    ports:
      - "5555:5555"
    depends_on:
      - celery
      - redis
    env_file:
      - .env
    volumes:
      - .:/code/
    <<: *common

  postgres:
    image: postgres:13.3-buster
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - project_postgres_data:/var/lib/postgresql/data/
    <<: *common

  redis:
    image: redis:6.2-buster
    ports:
      - "6379:6379"
    volumes:
      - project_redis_data:/data
    <<: *common

volumes:
  project_postgres_data:
  project_redis_data:
  project_static_volume:
  project_media_volume:
