version: "3.4"

x-common: &common
  stdin_open: true
  tty: true
  restart: unless-stopped

services:
  #  certbot:
  #    image: certbot/certbot
  #    container_name: ${PROJECT}-le01
  #    volumes:
  #      - ./data/certbot/conf:/etc/letsencrypt
  #      - ./data/certbot/www:/var/www/certbot
  ##    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  #    <<: *common

  nginx:
    image: nginx:1.20.1
    container_name: ${PROJECT}-nc01
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${NGINX_CONFIG_FILE}:/etc/nginx/conf.d/default.conf
      - ./data/django-static:/code/static
      - ./data/django-media:/code/media
    #      - ./data/certbot/conf:/etc/letsencrypt
    #      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - django
    #    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    <<: *common
