version: "3.4"

x-common: &common
  stdin_open: true
  tty: true
  restart: unless-stopped

x-django-build: &django-build
  build:
    context: .
    args:
      REQUIREMENT_FILE: $REQUIREMENT_FILE

services:
  celery:
    <<: [*django-build, *common]
    command: bash -c "NEW_RELIC_CONFIG_FILE=newrelic.ini newrelic-admin run-program celery -A e_commerce worker -l info"
    depends_on:
      - django
    env_file:
      - .env
    volumes:
      - ./:/code

  celery_beat:
    <<: [*django-build, *common]
    command: bash -c "NEW_RELIC_CONFIG_FILE=newrelic.ini newrelic-admin run-program celery -A e_commerce beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - django
    env_file:
      - .env
    volumes:
      - ./:/code

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    <<: *common

  django:
    <<: [*django-build, *common]
    command: bash -c "NEW_RELIC_CONFIG_FILE=newrelic.ini newrelic-admin run-program gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers $GUNICORN_WORKERS --worker-class gthread --threads $GUNICORN_THREADS"
    ports:
      - "8000"
    env_file:
      - .env
    volumes:
      - ./:/code

  flower:
    <<: [*django-build, *common]
    command: bash -c "NEW_RELIC_CONFIG_FILE=newrelic.ini newrelic-admin run-program celery -A e_commerce flower --conf=/code/config/settings/flowerconfig.py"
    ports:
      - "5555"
    depends_on:
      - celery
    env_file:
      - .env
    volumes:
      - .:/code/

  newrelic:
    image: newrelic/infrastructure:latest
    cap_add:
      - SYS_PTRACE
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      NRIA_LICENSE_KEY: $NRIA_LICENSE_KEY

  nginx:
    image: nginx:1.20.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - django
      - flower
    env_file:
      - .env
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    <<: *common
