version: "3.4"

x-common: &common
  stdin_open: true
  tty: true
  restart: unless-stopped

x-django-build: &django-build
  build:
    context: .
    args:
      REQUIREMENT_FILE: $REQUIREMENT_FILE
      USER: $USER

services:
  celery:
    <<: *django-build
    command: bash -c "python3 -m celery -A $PROJECT worker -l info"
    depends_on:
      - django
      - redis
    env_file:
      - $ENV_FILE
    volumes:
      - ./:/home/${USER}/code
    <<: *common

  celery_beat:
    <<: *django-build
    command: bash -c "python3 -m celery -A $PROJECT beat -l info"
    depends_on:
      - django
      - redis
    env_file:
      - $ENV_FILE
    volumes:
      - ./:/home/${USER}/code
    <<: *common

  certbot:
    image: certbot/certbot
#    volumes:
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot
##    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    <<: *common

  django:
    <<: *django-build
    command: bash -c "python3 -m gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers $GUNICORN_WORKERS --worker-class gthread --threads $GUNICORN_THREADS"
    ports:
      - "8000"
    env_file:
      - $ENV_FILE
    volumes:
      - ./:/home/${USER}/code
      - ./data/django-static:/code/static
      - ./data/django-media:/code/media
      - ~/.gitconfig:/etc/gitconfig
      - ~/.ssh:/home/${USER}/.ssh:ro
    depends_on:
      - postgres
      - redis
    <<: *common

  flower:
    image: mher/flower:0.9.7
    command: bash -c "python3 -m celery -A $PROJECT --broker=$REDIS_URL/0 flower --url_prefix=flower --basic_auth=$FLOWER_USERNAME:$FLOWER_PASSWORD"
    ports:
      - "5555"
    depends_on:
      - redis
    <<: *common

  nginx:
    image: nginx:1.20.1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/stage.conf:/etc/nginx/conf.d/stage.conf
      - ./data/django-static:/code/static
      - ./data/django-media:/code/media
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - django
      - flower
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    <<: *common

  postgres:
    image: postgres:13.3-buster
    env_file:
      - $ENV_FILE
    ports:
      - "5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    <<: *common

  redis:
    image: redis:6.2-buster
    ports:
      - "6379"
    volumes:
      - ./data/redis:/data
    <<: *common
