version: '3'

services:

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    container_name: project-cc01
    restart: unless-stopped
    command: bash -c "celery -A project worker -l info"
    depends_on:
      - django
      - redis
    env_file:
      - ./config/env/prod/.django
    volumes:
      - .:/code/
    networks:
      - internal

  celery_beat:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    container_name: project-cb01
    restart: unless-stopped
    command: bash -c "celery -A project beat -l info"
    depends_on:
      - django
      - redis
    env_file:
      - ./config/env/prod/.django
    volumes:
      - .:/code/
    networks:
      - default

  django:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    container_name: project-dc01
    restart: unless-stopped
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./config/env/prod/.django
    volumes:
      - ./:/code
      - project_static_volume:/code/static
      - project_media_volume:/code/media
    depends_on:
      - postgres
    networks:
      - default

  flower:
    image: mher/flower:0.9.7
    container_name: project-fc01
    restart: unless-stopped
    command: ["flower", "--broker=redis://redis:6379/0", "--broker_api=redis://redis:6379/0", "--port=5555"]
    ports:
      - 5555:5555
    networks:
      - default

  nginx:
    image: nginx:1.20.1
    container_name: project-nc01
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/prod/conf.d:/etc/nginx/conf.d/default.conf
      - project_static_volume:/code/static
      - project_media_volume:/code/media
    depends_on:
      - django
    networks:
      - default

  postgres:
    image: postgres:13.3-buster
    container_name: project-pc01
    restart: unless-stopped
    env_file:
      - ./config/env/prod/.postgres
    ports:
      - 5432:5432
    volumes:
      - project_postgres_data:/var/lib/postgresql/data/
    networks:
      - default

  redis:
    image: redis:6.2-buster
    container_name: project-rc01
    restart: unless-stopped
    volumes:
      - project_redis_data:/data
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  project_postgres_data:
  project_redis_data:
  project_static_volume:
  project_media_volume:
