version: '3'

services:

  postgres:
    image: postgres:13.0-alpine
    container_name: project-pc01
    env_file:
      - ./config/env/dev/.postgres
    ports:
      - 5432:5432
    volumes:
      - project_postgres_data:/var/lib/postgresql/data/
    networks:
      - internal

  redis:
    image: "redis:6.2-buster"
    container_name: project-rc01
    volumes:
      - project_redis_data:/data
    networks:
      - internal

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: project-cc01
    command: celery -A project worker -l info
    depends_on:
      - django
      - redis
    env_file:
      - ./config/env/dev/.django
    volumes:
      - .:/code/
    networks:
      - internal

  celery_beat:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: project-cb01
    command: celery -A project beat -l info
    depends_on:
      - django
      - redis
    env_file:
      - ./config/env/dev/.django
    volumes:
      - .:/code/
    networks:
      - internal

  flower:
    image: mher/flower
    container_name: project-fc01
    command: flower --broker=redis://redis:6379/0 --broker_api=redis://redis:6379/0 --port=5555
    ports:
      - 5555:5555

  django:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: project-dc01
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./config/env/dev/.django
    restart: always
    volumes:
      - ./:/code
      - project_static_volume:/code/static
      - project_media_volume:/code/media
    depends_on:
      - postgres
    networks:
      - internal

  nginx:
    image: nginx:1.17
    container_name: project-nc01
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/dev/conf.d:/etc/nginx/conf.d/default.conf
      - project_static_volume:/code/static
      - project_media_volume:/code/media
    depends_on:
      - django
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  project_postgres_data:
  project_redis_data:
  project_static_volume:
  project_media_volume:
