name: Bug
description: Report a bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: platform
    attributes:
      label: Platform
      description: On which platform(s) did this bug occurred?
      placeholder: dev, stage, prod
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce
      placeholder: 1. step one
    validations:
      required: false
  - type: input
    id: sentry
    attributes:
      label: Sentry
      description: Sentry link (if any).
    validations:
      required: false
  - type: input
    id: datadog
    attributes:
      label: Datadog
      description: Datadog link (if any).
    validations:
      required: false
  - type: textarea
    id: implementation-detail
    attributes:
      label: Implementation detail
      description: Implementation detail
    validations:
      required: false
  - type: textarea
    id: testing-instructions
    attributes:
      label: Testing instructions
      description: Testing Instructions
    validations:
      required: false
