name: project

on: [push]

jobs:

  django-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make dev.test
      - uses: actions/upload-artifact@v2
        with:
          name: django-coverage-report
          path: htmlcov
